// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ITUdatabase_GetStudents_FullMethodName = "/ITUdatabase/GetStudents"
)

// ITUdatabaseClient is the client API for ITUdatabase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ITUdatabaseClient interface {
	GetStudents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Students, error)
}

type iTUdatabaseClient struct {
	cc grpc.ClientConnInterface
}

func NewITUdatabaseClient(cc grpc.ClientConnInterface) ITUdatabaseClient {
	return &iTUdatabaseClient{cc}
}

func (c *iTUdatabaseClient) GetStudents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Students, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Students)
	err := c.cc.Invoke(ctx, ITUdatabase_GetStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITUdatabaseServer is the server API for ITUdatabase service.
// All implementations must embed UnimplementedITUdatabaseServer
// for forward compatibility.
type ITUdatabaseServer interface {
	GetStudents(context.Context, *Empty) (*Students, error)
	mustEmbedUnimplementedITUdatabaseServer()
}

// UnimplementedITUdatabaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedITUdatabaseServer struct{}

func (UnimplementedITUdatabaseServer) GetStudents(context.Context, *Empty) (*Students, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}
func (UnimplementedITUdatabaseServer) mustEmbedUnimplementedITUdatabaseServer() {}
func (UnimplementedITUdatabaseServer) testEmbeddedByValue()                     {}

// UnsafeITUdatabaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ITUdatabaseServer will
// result in compilation errors.
type UnsafeITUdatabaseServer interface {
	mustEmbedUnimplementedITUdatabaseServer()
}

func RegisterITUdatabaseServer(s grpc.ServiceRegistrar, srv ITUdatabaseServer) {
	// If the following call pancis, it indicates UnimplementedITUdatabaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ITUdatabase_ServiceDesc, srv)
}

func _ITUdatabase_GetStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITUdatabaseServer).GetStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ITUdatabase_GetStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITUdatabaseServer).GetStudents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ITUdatabase_ServiceDesc is the grpc.ServiceDesc for ITUdatabase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ITUdatabase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ITUdatabase",
	HandlerType: (*ITUdatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudents",
			Handler:    _ITUdatabase_GetStudents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
